services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: student-mara-db
    environment:
      SA_PASSWORD: "ConcertTicket@2024"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    expose:
      - "1433"
    networks:
      - studlab_net
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/1433' 2>/dev/null && echo OK"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  api:
    container_name: student-mara-api
    build:
      context: .
      dockerfile: Dockerfile.api
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=student-mara-db;Database=ConcertTicketPlatformDb;User Id=sa;Password=ConcertTicket@2024;TrustServerCertificate=True;
      - Jwt__Key=SuperSecretKey_ConcertTicket_2024_MinLength32Chars
      - Jwt__Issuer=ConcertTicketAPI
      - Jwt__Audience=ConcertTicketWeb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - studlab_net
    restart: on-failure

  web:
    container_name: student-mara-frontend
    build:
      context: .
      dockerfile: Dockerfile.web
    expose:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__DefaultConnection=Server=student-mara-db;Database=ConcertTicketPlatformDb;User Id=sa;Password=ConcertTicket@2024;TrustServerCertificate=True;
      - ApiBaseUrl=http://student-mara-api:8080/
      - ApiPublicUrl=
    depends_on:
      - api
    networks:
      - studlab_net
    restart: on-failure

networks:
  studlab_net:
    external: true

volumes:
  sqldata:
