// <auto-generated />
using System;
using ConcertTicketPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcertTicketPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605120000_AddArtistCategoryManyToMany")]
    partial class AddArtistCategoryManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtistCategories", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ArtistId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ArtistCategories");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");
                    b.Property<int>("AccessFailedCount").HasColumnType("int");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<bool>("EmailConfirmed").HasColumnType("bit");
                    b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("LockoutEnabled").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
                    b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
                    b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
                    b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
                    b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
                    b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
                    b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Artist", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Bio").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Genre").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ImageUrl").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Artists");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Concert", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("ArtistId").HasColumnType("int");
                    b.Property<int>("AvailableSeats").HasColumnType("int");
                    b.Property<int>("CategoryId").HasColumnType("int");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("TotalSeats").HasColumnType("int");
                    b.Property<int>("VenueId").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("ArtistId");
                    b.HasIndex("CategoryId");
                    b.HasIndex("VenueId");
                    b.ToTable("Concerts");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Review", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Comment").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("ConcertId").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("Rating").HasColumnType("int");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("ConcertId");
                    b.HasIndex("UserId");
                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("ConcertId").HasColumnType("int");
                    b.Property<bool>("IsUsed").HasColumnType("bit");
                    b.Property<DateTime>("PurchasedAt").HasColumnType("datetime2");
                    b.Property<string>("SeatNumber").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("ConcertId");
                    b.HasIndex("UserId");
                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Venue", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Address").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("Capacity").HasColumnType("int");
                    b.Property<string>("City").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id").HasColumnType("nvarchar(450)");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL");
                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                    b.Property<string>("RoleId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
                    b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)");
                    b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                    b.Property<string>("RoleId").HasColumnType("nvarchar(450)");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId").HasColumnType("nvarchar(450)");
                    b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
                    b.Property<string>("Name").HasColumnType("nvarchar(450)");
                    b.Property<string>("Value").HasColumnType("nvarchar(max)");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArtistCategories", b =>
                {
                    b.HasOne("ConcertTicketPlatform.Core.Entities.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("ConcertTicketPlatform.Core.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Concert", b =>
                {
                    b.HasOne("ConcertTicketPlatform.Core.Entities.Artist", "Artist").WithMany("Concerts").HasForeignKey("ArtistId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("ConcertTicketPlatform.Core.Entities.Category", "Category").WithMany("Concerts").HasForeignKey("CategoryId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("ConcertTicketPlatform.Core.Entities.Venue", "Venue").WithMany("Concerts").HasForeignKey("VenueId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Artist");
                    b.Navigation("Category");
                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Review", b =>
                {
                    b.HasOne("ConcertTicketPlatform.Core.Entities.Concert", "Concert").WithMany("Reviews").HasForeignKey("ConcertId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("ConcertTicketPlatform.Core.Entities.AppUser", "User").WithMany("Reviews").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Concert");
                    b.Navigation("User");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Ticket", b =>
                {
                    b.HasOne("ConcertTicketPlatform.Core.Entities.Concert", "Concert").WithMany("Tickets").HasForeignKey("ConcertId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("ConcertTicketPlatform.Core.Entities.AppUser", "User").WithMany("Tickets").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Concert");
                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ConcertTicketPlatform.Core.Entities.AppUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ConcertTicketPlatform.Core.Entities.AppUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("ConcertTicketPlatform.Core.Entities.AppUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ConcertTicketPlatform.Core.Entities.AppUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.AppUser", b =>
                {
                    b.Navigation("Reviews");
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Artist", b =>
                {
                    b.Navigation("Concerts");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Category", b =>
                {
                    b.Navigation("Concerts");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Concert", b =>
                {
                    b.Navigation("Reviews");
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ConcertTicketPlatform.Core.Entities.Venue", b =>
                {
                    b.Navigation("Concerts");
                });
#pragma warning restore 612, 618
        }
    }
}
